---
AWSTemplateFormatVersion: 2010-09-09
Description: This is a CloudFormation template to create CloudTrail logging infrastructure to S3 and CloudWatch Logs - https://aws.amazon.com/cloudtrail/


Parameters:
  service:
    Type: String
    Description: service name
    Default: splunk-aws-gdi-toolkit

  stage:
    Type: String
    Description: Used to distinguish between stages of an environment
    Default: dev

  contact:
    Description: Used to identify a contact for the resources created in this stack.  As an example, this could be an email address or username.
    Type: String

  cloudTrailLogFileValidation:
    Description: Used to enable or disable CloudTrail File Validation - https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-validation-intro.html .
    Default: true
    Type: String
    AllowedValues:
      - true
      - false

  cloudTrailIncludeGlobalServiceEvents:
    Description: Used to enable or disable logging of CloudTrail global service events - https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-concepts.html#cloudtrail-concepts-global-service-events .
    Default: true
    Type: String
    AllowedValues:
      - true
      - false

  cloudTrailMultiRegionLogging:
    Description: Used to enable or disable logging of CloudTrail logs from all regions.
    Default: true
    Type: String
    AllowedValues:
      - true
      - false

  cloudTrailS3FileExpirationInDays:
    Description: How many days to keep the CloudTrail files in S3.
    Default: 366
    Type: String


Resources:
  cloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt cloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt cloudTrailRole.Arn
      EnableLogFileValidation: !Ref cloudTrailLogFileValidation
      IncludeGlobalServiceEvents: !Ref cloudTrailIncludeGlobalServiceEvents
      IsLogging: true
      IsMultiRegionTrail: !Ref cloudTrailMultiRegionLogging
      S3BucketName: !Ref cloudTrailS3Bucket
      Tags:
      - Key: service
        Value: !Ref service
      - Key: stage
        Value: !Ref stage
      - Key: contact
        Value: !Ref contact
      TrailName: !Sub "${service}-cloudtrail"

  cloudTrailPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:Describe*
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: !GetAtt cloudTrailLogGroup.Arn
        - Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub "arn:aws:s3:::${AWS::AccountId}-cloudtrail-bucket/*"
        - Effect: Allow
          Action:
          - s3:GetBucketAcl
          Resource: !Sub "arn:aws:s3:::${AWS::AccountId}-cloudtrail-bucket"
      ManagedPolicyName: !Sub "${service}-cloudtrail-iam-policy"

  cloudTrailRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "cloudtrail.amazonaws.com"
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref cloudTrailPolicy
      RoleName: !Sub "${service}-cloudtrail-iam-role"
      Tags:
      - Key: service
        Value: !Ref service
      - Key: stage
        Value: !Ref stage
      - Key: contact
        Value: !Ref contact

  cloudTrailS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub "${AWS::AccountId}-cloudtrail-bucket"
      LifecycleConfiguration:
        Rules:
            - Id: !Sub "${AWS::AccountId}-cloudtrail-bucket-cleanupPolicy"
              AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 1
              Status: Enabled
            - Id: !Sub "${service}-infralog-bucket-expiration"
              ExpirationInDays: !Ref cloudTrailS3FileExpirationInDays
              Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
      - Key: service
        Value: !Ref service
      - Key: stage
        Value: !Ref stage
      - Key: contact
        Value: !Ref contact

  cloudTrailS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref cloudTrailS3Bucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
            - s3:GetBucketAcl
          Principal: 
            Service: cloudtrail.amazonaws.com
          Resource: !Sub "arn:aws:s3:::${AWS::AccountId}-cloudtrail-bucket"
        - Effect: Allow
          Action:
            - s3:PutObject
          Principal: 
            Service: cloudtrail.amazonaws.com
          Resource: !Sub "arn:aws:s3:::${AWS::AccountId}-cloudtrail-bucket/AWSLogs/${AWS::AccountId}/*"

  cloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${service}-cloudtrail/"
      RetentionInDays: 7


Outputs:
  cloudTrailArn: 
    Value: !GetAtt cloudTrail.Arn
  cloudTrailRoleArn:
    Value: !GetAtt cloudTrailRole.Arn
  cloudTrailS3BucketArn:
    Value: !GetAtt cloudTrailS3Bucket.Arn
  cloudTrailLogGroupArn:
    Value: !GetAtt cloudTrailLogGroup.Arn