---
AWSTemplateFormatVersion: 2010-09-09
Description: This is a CloudFormation template to enable GuardDuty - https://aws.amazon.com/guardduty/


Parameters:
  service:
    Type: String
    Description: service name
    Default: splunk-aws-gdi-tooklit

  stage:
    Type: String
    Description: Used to distinguish between stages of an environment
    Default: dev

  contact:
    Description: Used to identify a contact for the resources created in this stack.  As an example, this could be an email address or username.
    Type: String

Resources:
  guardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties: 
      Enable: true
      FindingPublishingFrequency: FIFTEEN_MINUTES


Outputs:
  guardDutyDetector:
    Value: !Ref guardDutyDetector